#!/usr/bin/env bash
#Installs and configure HAproxy on your lb-01 load balancer server.

sudo apt-get update
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.7 -y
sudo apt-get install -y haproxy=2.7.\*

#configuring HAproxy

sudo cat <<EOF | sudo tee -a /etc/haproxy/haproxy.cfg
frontend ALX_load_balancer
	bind *:80
	mode http
	default_backend ALX_web_servers
backend ALX_web_servers
	balance roundrobin
	server 106237-web-01 54.146.75.232:80 check
	server 106237-web-02 34.207.227.49:80 check
EOF

sudo /etc/init.d/haproxy restart
