#!/usr/bin/env bash
#configures a new Ubuntu machine nginx

apt-get update
apt-get apt-get -y install haproxy=1.7.\*
echo "ENABLED=1" >> /etc/default/haproxy
sed -i '/504.http/a \\nlisten http-in\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\tserver 106237-web-01 54.157.141.132:80 check\n\tserver 106237-web-02 54.158.220.204:80 check' /etc/haproxy/haproxy.cfg
sudo service haproxy start
