#!/usr/bin/env bash
# Ping an address from cmd arg 5 times

if [ $# -eq 0 ]; then
  echo "Usage: $0 {IP_ADDRESS}"
  exit 1
fi

# Get the IP address argument
ip_address=$1

# Ping the IP address 5 times
for ((i=1; i<=5; i++)); do
  echo "Pinging $ip_address..."
  ping -c 1 "$ip_address"
done
