#!/usr/bin/env bash
# fix nginx listening port and relaods nginx master process

sed -i 's/listen 8080/listen 80/g' /etc/nginx/sites-enable/default
sed -i 's/listen \[::\]:8080/listen \[::\]:80/g' /etc/nginx/sites-enabled/default
pgrep nginx -o > /run/nginx.pid
nginx -s reload
echo '' > /run/nginx.pid
