#!/usr/bin/env bash
# fixing nginx listening on port 80

cd /etc/nginx/sites-enabled/ || exit;

# delet the dafault file

rm default;

# create symbolic link to the default file in sites-available

ln -s /etc/nginx/sites-available/default default;

# restart nginx

service nginx restart
