#!/usr/bin/env bash
server {
    listen 80;
    server_name 54.174.86.115;

    location /airbnb-onepage/ {
        proxy_pass http://localhost:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
