#!/usr/bin/env bash
# serves page from the route /airbnb-onepage/

server {
    listen 80;
    server_name localhost;  # Serve locally
    root /etc/nginx/html; 

    location /airbnb-onepage/ {
        proxy_pass http://127.0.0.1:5000/;  # Proxy requests to the Flask app
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 80;
    server_name 54.174.86.115;  # Serve on public IP
    root /etc/nginx/html; 

    location /airbnb-onepage/ {
        proxy_pass http://127.0.0.1:5000/;  # Proxy requests to the Flask app
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

