#!/usr/bin/env bash
# serves page from the route /airbnb-onepage/

server {
    listen 80;
    server_name localhost;  # Serve locally
    root /path/to/your/flask/app;  # Replace with the path to your Flask app

    location /airbnb-onepage/ {
        proxy_pass http://127.0.0.1:5000/;  # Proxy requests to the Flask app
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 80;
    server_name your_public_ip;  # Serve on public IP
    root /path/to/your/flask/app;  # Replace with the path to your Flask app

    location /airbnb-onepage/ {
        proxy_pass http://127.0.0.1:5000/;  # Proxy requests to the Flask app
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

